"""Tiny smoke-test variant of the visual-Sudoku SFT config.

Inherits ``sft_sudoku_vision_full.get_config()`` and swaps the 26B_A4B
backbone for a topologically-identical *tiny* model (CPU-friendly), keeping
the task, data pipeline, trainer, losses and optimizer structure intact.

Tiny dimensions follow the design walkthrough's tiny/smoke column
(docs/add-visual-inputs/index.html §9): D=32, 3 blocks (2x LOCAL_SLIDING +
1x GLOBAL), N_h=4, N_kv=2, d_h=8, K_g=16, N_gkv=1, H_f=48, MoE E=4/top-2/
E_d=16; vision tower D_v=16, 2 layers, 2 heads, ffw 32, S_max=280.

Deliberate deviations from that column, so the tiny config still "configures
the same task" end to end:
  * The **sequence geometry keeps the full design values** (P=384, CS=256,
    NC=1 -> FS=C=640, P_p=2520, p_d=768) so a smoke run reproduces exactly
    the tensor shapes of the design's shape tables.
  * The **vocabulary stays at 262,144** because the tiny config consumes the
    real visual-sudoku data through the real Gemma4 tokenizer (the design's
    V=64 tiny value belonged to a synthetic-token component smoke).
  * ``sliding_window_size`` stays 1024 (> FS = 640) so the window never
    binds, matching the design note.

Also: batch size 2, 1 train step, constant LR, no checkpoint loading, no
evals, in-process data loading — a single forward+backward+optimizer-update
finishes on CPU in well under 3 minutes.

The smoke-test Bagz files are generated by
``ft_gemma/diffusion/scripts/train_sudoku_vision_smoke.sh`` via
``convert_sudoku_vision.py --fake_records``.
"""

from ft_gemma.diffusion.hackable_diffusion_adapter.configs import sft_sudoku_vision_full
from kauldron import konfig

# pylint: disable=g-import-not-at-top
with konfig.imports():
  from ft_gemma.diffusion.hackable_diffusion_adapter.hd import vision_gemma_model
  from gemma.gm.nn.gemma4 import _config
  from gemma.gm.nn.gemma4 import _modules
  from gemma.gm.nn.gemma4.vision import _encoder as gemma_vision
  from kauldron import kd
  import optax
# pylint: enable=g-import-not-at-top

_FAKE_DATA_DIR = "ft_gemma/diffusion/hackable_diffusion_adapter/data/sudoku/smoke"


def get_config():
  """Tiny visual-Sudoku SFT config for CPU smoke testing."""
  cfg = sft_sudoku_vision_full.get_config()

  ##############################################################################
  # Tiny backbone + tiny vision tower (same topology as 26B_A4B + vision).
  ##############################################################################
  tiny_vision_encoder = gemma_vision.VisionEncoder(
      d_model=16,
      num_layers=2,
      num_heads=2,
      ffw_hidden=32,
      output_length=280,  # S_max — must equal aux.max_soft_tokens_per_image.
      use_clipped_linears=False,
      standardize_embeddings=True,
  )
  tiny_config = _config.TransformerConfig(
      num_embed=262_144,  # real Gemma4 vocab (real tokenizer / real data)
      embed_dim=32,
      hidden_dim=48,  # Dense shared MLP (mlp2) hidden dim
      num_heads=4,
      head_dim=8,
      num_kv_heads=2,
      final_logit_softcap=30.0,
      num_global_kv_heads=1,
      use_post_attn_norm=True,
      use_post_ffw_norm=True,
      qk_norm_with_scale=True,
      attention_types=[
          _modules.AttentionType.LOCAL_SLIDING,
          _modules.AttentionType.LOCAL_SLIDING,
          _modules.AttentionType.GLOBAL,
      ],
      global_key_size=16,
      k_eq_v_global=True,
      global_rope_proportion=0.25,
      local_rope_proportion=1.0,
      attn_logits_soft_cap=None,
      sliding_window_size=1024,  # > FS=640 — the window never binds.
      local_base_frequency=10_000,
      global_base_frequency=1_000_000,
      per_layer_input_dim=0,
      # MoE configuration
      enable_moe=True,
      num_experts=4,
      expert_dim=16,
      top_k_experts=2,
      moe_dense_hidden_dim=48,
      vision_encoder=tiny_vision_encoder,
      use_bidirectional_attention="vision",
  )
  cfg.model.gemma_network.gemma_model = (
      vision_gemma_model.VisionDiffusionGemma_26B_A4B(
          config=tiny_config,
          text_only=False,
      )
  )

  ##############################################################################
  # Smoke-run trainer settings.
  ##############################################################################
  cfg.num_train_steps = 1
  # Kauldron runs `num_train_steps + 1` loop iterations; cap at exactly one
  # optimizer update for the smoke run.
  cfg.stop_after_steps = 1
  # Constant LR so the single optimizer update visibly changes the params
  # (the full config's warmup schedule yields lr=0 at step 0).
  cfg.schedules["learning_rate"] = optax.constant_schedule(1e-3)
  # No 26B checkpoint to load for the tiny model.
  cfg.init_transform = None
  # Skip standalone evals / checkpoint export in the smoke run.
  cfg.evals = {}
  cfg.checkpointer = kd.ckpts.NoopCheckpointer()
  cfg.workdir = "/tmp/ft_gemma_sudoku_vision_smoke"

  ##############################################################################
  # Tiny data settings: fake visual-sudoku Bagz, small batch, in-process.
  ##############################################################################
  for ds, split in ((cfg.train_ds, "train"), (cfg.eval_ds, "eval")):
    ds.bagz_path = f"{_FAKE_DATA_DIR}/sudoku_vision_{split}.bagz"
    ds.batch_size = 2
    ds.num_workers = 0
  cfg.eval_ds.slice_stop = None

  return cfg
